### ISSUE TITLE
Bug: Missing button for select native variants on mobile site

### ISSUE THREAD

**Issue by zbanaw** [AeonSake/acnh-catalogue-issues#29] opened 2022-06-08 01:58 UTC
On the mobile site, the "Select native item variant" option pop up screen is missing the 'Cancel' and 'Done' buttons or they are rendering off the screen. This makes it difficult to save the settings. The buttons are reachable in the desktop site, but should be reachable in mobile site as well.

![Screenshot_20220607-211840_Chrome](https://user-images.githubusercontent.com/9644945/172514364-8e381c40-9493-4993-b768-601f7f95021d.jpg)

**Comment by AeonSake** [comment] 2022-06-10 10:23
Hmm strange, this is usually an issue with iOS browsers but that looks like Android? What browser (and version) are you using? It kinda looks like the entire dialog is cut off since not even the entire scrollbar is shown.

**Comment by zbanaw** [comment] 2022-06-10 10:32
Yes, it's an Android and Chrome version 102.0.5005.78.

**Comment by AeonSake** [comment] 2022-06-10 12:21
I have identified the issue. It's caused by the floating header/toolbar/navigation bar which changes the total page height. Dialogs scale to a max of 100% of the screen height but it's reported incorrectly due to the toolbar. I will publish a fix in the next few days. Sorry for the inconvenience. In the meantime you can manually zoom out until you see the buttons for now.

**Comment by zbanaw** [comment] 2022-06-10 12:50
No problem. I did switch to the desktop version briefly to save the settings. Just other people may not know how to do that. As a developer too, I understand that these things happen. 😅 Thanks again.

**Comment by AeonSake** [comment] 2022-06-11 13:58
The issue should now be fixed with the latest update (v3.341).

**Closed as completed** 2022-06-24 13:15 UTC
